// excs.js — conversion between .excalidraw scenes and the compact .excs text
// format. Loaded as a classic script by excalidraw-file-sync.html (file://
// pages can't import ES modules) and via require() by exc.mjs for CLI use.
//
// .excs is an EPHEMERAL projection of the .excalidraw file, regenerated by the
// bridge on every sync — edit it, never treat it as the source of truth.
//
// Format: one element per line, line order = z-order.
//   @scene {"type":"excalidraw",...}                        header (appState, files)
//   rect|ellipse|diamond <id> <x>,<y> <w>x<h> [k=v|flag]* ["bound text"]
//   text <id> <x>,<y> [k=v]* "text"
//   arrow|line <id> <x,y;x,y;...> [k=v|flag]* ["label"]
//   json {...}                                              passthrough (images, frames, ...)
// Keys: stroke bg sw op angle groups link fs ff tc talign align from to lfs ltc lxy
// (link lives on the container line only; bound text never carries one)
// Flags: dashed dotted sharp locked noend startarrow elbowed
// Defaults elided on dump: stroke #1e1e1e, bg transparent, sw 2, op 100,
// ff 3 (code font), rects rounded, arrows end-arrowhead only, bound text
// centered #1e1e1e. Numbers are rounded to 2 decimals.

(function (root) {
  "use strict";

  var D = { stroke: "#1e1e1e", bg: "transparent", sw: 2, op: 100, ff: 3, fs: 12 };
  var MODELED = { rectangle: 1, ellipse: 1, diamond: 1, text: 1, arrow: 1, line: 1 };

  function r2(n) { return Math.round(n * 100) / 100; }
  function estW(text, fs) {
    var lines = text.split("\n"), m = 0;
    for (var i = 0; i < lines.length; i++) m = Math.max(m, lines[i].length);
    return m * fs * 0.6;
  }
  function estH(text, fs) { return text.split("\n").length * fs * 1.25; }
  function q(s) { return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"'; }
  function unq(s) { return s.replace(/\\n/g, "\n").replace(/\\"/g, '"').replace(/\\\\/g, "\\"); }
  // stable per-id seed so a rebuild never churns the file
  function seedOf(id) {
    var h = 5381;
    for (var i = 0; i < id.length; i++) h = ((h * 33) ^ id.charCodeAt(i)) >>> 0;
    return h || 1;
  }

  // ------------------------------------------------------------------ dump
  function dump(scene) {
    var els = (scene.elements || []).filter(function (e) { return !e.isDeleted; });
    var byId = {};
    els.forEach(function (e) { byId[e.id] = e; });

    // bound text folds into its container's line, but only for modeled containers
    var boundText = {};
    els.forEach(function (e) {
      if (e.type === "text" && e.containerId && byId[e.containerId]
        && MODELED[byId[e.containerId].type] && !boundText[e.containerId]) {
        boundText[e.containerId] = e;
      }
    });
    var folded = {};
    Object.keys(boundText).forEach(function (k) { folded[boundText[k].id] = 1; });

    var out = [];
    var header = {};
    Object.keys(scene).forEach(function (k) { if (k !== "elements") header[k] = scene[k]; });
    out.push("@scene " + JSON.stringify(header));

    els.forEach(function (e) {
      if (folded[e.id]) return;
      var kv = [];
      function attr(k, v, dflt) { if (v !== undefined && v !== null && v !== dflt) kv.push(k + "=" + v); }
      function flag(cond, f) { if (cond) kv.push(f); }
      function common() {
        attr("stroke", e.strokeColor, D.stroke);
        attr("bg", e.backgroundColor, D.bg);
        attr("sw", e.strokeWidth, D.sw);
        attr("op", e.opacity, D.op);
        if (e.angle) kv.push("angle=" + r2(e.angle));
        if (e.groupIds && e.groupIds.length) kv.push("groups=" + e.groupIds.join(","));
        flag(e.strokeStyle === "dashed", "dashed");
        flag(e.strokeStyle === "dotted", "dotted");
        flag(e.locked, "locked");
        if (e.link) kv.push("link=" + e.link);
      }
      function foldedText() {
        var t = boundText[e.id];
        if (!t) return "";
        kv.push((e.type === "arrow" || e.type === "line" ? "lfs=" : "fs=") + t.fontSize);
        attr("ff", t.fontFamily, D.ff);
        if (e.type === "arrow" || e.type === "line") {
          if (t.strokeColor !== D.stroke) kv.push("ltc=" + t.strokeColor);
          kv.push("lxy=" + r2(t.x) + "," + r2(t.y));
        } else {
          if (t.strokeColor !== D.stroke) kv.push("tc=" + t.strokeColor);
          if (t.textAlign && t.textAlign !== "center") kv.push("talign=" + t.textAlign);
        }
        return " " + q(t.text);
      }

      if (e.type === "rectangle" || e.type === "ellipse" || e.type === "diamond") {
        var kind = e.type === "rectangle" ? "rect" : e.type;
        common();
        flag(e.type === "rectangle" && !e.roundness, "sharp");
        var txt = foldedText();
        out.push(kind + " " + e.id + " " + r2(e.x) + "," + r2(e.y) + " "
          + r2(e.width) + "x" + r2(e.height) + fmt(kv) + txt);
      } else if (e.type === "text") {
        kv.push("fs=" + e.fontSize);
        attr("ff", e.fontFamily, D.ff);
        attr("stroke", e.strokeColor, D.stroke);
        attr("op", e.opacity, D.op);
        if (e.textAlign && e.textAlign !== "left") kv.push("align=" + e.textAlign);
        if (e.angle) kv.push("angle=" + r2(e.angle));
        if (e.link) kv.push("link=" + e.link);
        out.push("text " + e.id + " " + r2(e.x) + "," + r2(e.y) + fmt(kv) + " " + q(e.text));
      } else if (e.type === "arrow" || e.type === "line") {
        common();
        if (e.startBinding && e.startBinding.elementId) kv.push("from=" + e.startBinding.elementId);
        if (e.endBinding && e.endBinding.elementId) kv.push("to=" + e.endBinding.elementId);
        flag(e.elbowed, "elbowed");
        flag(e.type === "arrow" && e.endArrowhead == null, "noend");
        flag(e.startArrowhead != null, "startarrow");
        var pts = e.points.map(function (p) { return r2(e.x + p[0]) + "," + r2(e.y + p[1]); }).join(";");
        var lbl = foldedText();
        out.push(e.type + " " + e.id + " " + pts + fmt(kv) + lbl);
      } else {
        // passthrough: keep verbatim, minus arrow backrefs (rebuilt on build)
        var copy = {};
        Object.keys(e).forEach(function (k) { copy[k] = e[k]; });
        if (Array.isArray(copy.boundElements)) {
          copy.boundElements = copy.boundElements.filter(function (b) { return b.type === "text"; });
          if (!copy.boundElements.length) delete copy.boundElements;
        }
        out.push("json " + JSON.stringify(copy));
      }
    });
    return out.join("\n") + "\n";
  }
  function fmt(kv) { return kv.length ? " " + kv.join(" ") : ""; }

  // ----------------------------------------------------------------- build
  function tokenize(line) {
    var toks = [], re = /"((?:[^"\\]|\\.)*)"|(\S+)/g, m;
    while ((m = re.exec(line))) toks.push(m[1] !== undefined ? { str: unq(m[1]) } : m[2]);
    return toks;
  }

  function build(src) {
    var header = {
      type: "excalidraw", version: 2, source: "excs",
      appState: { viewBackgroundColor: "#ffffff" }, files: {}
    };
    var els = [], byId = {}, pending = [];
    function push(e) { els.push(e); byId[e.id] = e; return e; }
    function base(id) {
      return {
        angle: 0, fillStyle: "solid", strokeWidth: D.sw, strokeStyle: "solid",
        roughness: 0, opacity: D.op, groupIds: [], frameId: null,
        seed: seedOf(id), version: 1, versionNonce: seedOf(id + "n"),
        isDeleted: false, link: null, locked: false, updated: 1
      };
    }

    src.split("\n").forEach(function (raw, ln) {
      var line = raw.trim();
      if (!line || line.charAt(0) === "#") return;
      try {
        if (line.indexOf("@scene ") === 0) { header = JSON.parse(line.slice(7)); return; }
        if (line.indexOf("json ") === 0) {
          var pe = JSON.parse(line.slice(5));
          if (!pe.boundElements) pe.boundElements = [];
          push(pe);
          return;
        }
        buildLine(line);
      } catch (e) {
        throw new Error("line " + (ln + 1) + ": " + e.message + "  [" + line.slice(0, 60) + "]");
      }
    });

    function buildLine(line) {
      var toks = tokenize(line);
      var kind = toks.shift(), id = toks.shift();
      if (typeof id !== "string") throw new Error("missing id");
      var kv = {}, flags = {}, strs = [], coords = null, size = null, pts = null;
      toks.forEach(function (t) {
        if (typeof t === "object") { strs.push(t.str); return; }
        var i = t.indexOf("=");
        if (i > 0) { kv[t.slice(0, i)] = t.slice(i + 1); return; }
        if (/^-?[\d.]+,-?[\d.]+(;-?[\d.]+,-?[\d.]+)+$/.test(t)) {
          pts = t.split(";").map(function (p) { return p.split(",").map(Number); }); return;
        }
        if (/^-?[\d.]+,-?[\d.]+$/.test(t)) { coords = t.split(",").map(Number); return; }
        if (/^[\d.]+x[\d.]+$/.test(t)) { size = t.split("x").map(Number); return; }
        flags[t] = 1;
      });
      var common = {
        strokeColor: kv.stroke || D.stroke,
        backgroundColor: kv.bg || D.bg,
        strokeWidth: kv.sw ? Number(kv.sw) : D.sw,
        opacity: kv.op ? Number(kv.op) : D.op,
        strokeStyle: flags.dashed ? "dashed" : flags.dotted ? "dotted" : "solid",
        angle: kv.angle ? Number(kv.angle) : 0,
        groupIds: kv.groups ? kv.groups.split(",") : [],
        locked: !!flags.locked,
        link: kv.link || null
      };
      function boundTextEl(container, text, fs, color, at, talign) {
        var w = estW(text, fs), h = estH(text, fs);
        if (container.width) w = Math.min(w, container.width - 12);
        var pos = at || [
          container.x + (container.width || 0) / 2 - w / 2,
          container.y + (container.height || 0) / 2 - h / 2
        ];
        var t = push(Object.assign(base(container.id + "_t"), {
          type: "text", id: container.id + "_t", x: pos[0], y: pos[1], width: w, height: h,
          strokeColor: color, backgroundColor: "transparent", fillStyle: "solid",
          fontSize: fs, fontFamily: kv.ff ? Number(kv.ff) : D.ff,
          text: text, textAlign: talign || "center", verticalAlign: "middle",
          containerId: container.id, originalText: text, lineHeight: 1.25,
          roundness: null, boundElements: []
        }));
        container.boundElements.push({ id: t.id, type: "text" });
      }

      if (kind === "rect" || kind === "ellipse" || kind === "diamond") {
        if (!coords || !size) throw new Error("need <x>,<y> and <w>x<h>");
        var e = push(Object.assign(base(id), common, {
          type: kind === "rect" ? "rectangle" : kind, id: id,
          x: coords[0], y: coords[1], width: size[0], height: size[1],
          roundness: kind === "rect" && !flags.sharp ? { type: 3 } : null,
          boundElements: []
        }));
        if (strs.length) boundTextEl(e, strs[0], kv.fs ? Number(kv.fs) : D.fs, kv.tc || D.stroke, null, kv.talign);
      } else if (kind === "text") {
        if (!coords) throw new Error("need <x>,<y>");
        var fs = kv.fs ? Number(kv.fs) : D.fs, text = strs.length ? strs[0] : "";
        push(Object.assign(base(id), {
          type: "text", id: id, x: coords[0], y: coords[1],
          width: estW(text, fs), height: estH(text, fs),
          strokeColor: kv.stroke || D.stroke, backgroundColor: "transparent",
          opacity: kv.op ? Number(kv.op) : D.op, angle: kv.angle ? Number(kv.angle) : 0,
          link: kv.link || null, fontSize: fs, fontFamily: kv.ff ? Number(kv.ff) : D.ff, text: text,
          textAlign: kv.align || "left", verticalAlign: "top", containerId: null,
          originalText: text, lineHeight: 1.25, roundness: null, boundElements: []
        }));
      } else if (kind === "arrow" || kind === "line") {
        if (!pts) throw new Error("need <x,y;x,y;...> points");
        var sx = pts[0][0], sy = pts[0][1];
        var rel = pts.map(function (p) { return [p[0] - sx, p[1] - sy]; });
        var maxX = 0, minX = 0, maxY = 0, minY = 0;
        rel.forEach(function (p) {
          maxX = Math.max(maxX, p[0]); minX = Math.min(minX, p[0]);
          maxY = Math.max(maxY, p[1]); minY = Math.min(minY, p[1]);
        });
        var a = push(Object.assign(base(id), common, {
          type: kind, id: id, x: sx, y: sy, width: maxX - minX, height: maxY - minY,
          points: rel, lastCommittedPoint: null,
          startArrowhead: flags.startarrow ? "arrow" : null,
          endArrowhead: kind === "arrow" && !flags.noend ? "arrow" : null,
          startBinding: kv.from ? { elementId: kv.from, focus: 0, gap: 2 } : null,
          endBinding: kv.to ? { elementId: kv.to, focus: 0, gap: 2 } : null,
          roundness: flags.elbowed ? null : { type: 2 }, elbowed: !!flags.elbowed,
          boundElements: []
        }));
        if (kv.from) pending.push([kv.from, { id: id, type: "arrow" }]);
        if (kv.to) pending.push([kv.to, { id: id, type: "arrow" }]);
        if (strs.length) {
          var lfs = kv.lfs ? Number(kv.lfs) : 11;
          var at = kv.lxy ? kv.lxy.split(",").map(Number) : (function () {
            var i = Math.floor(pts.length / 2);
            return [
              (pts[i - 1][0] + pts[i][0]) / 2 - estW(strs[0], lfs) / 2,
              (pts[i - 1][1] + pts[i][1]) / 2 - estH(strs[0], lfs) / 2
            ];
          })();
          boundTextEl(a, strs[0], lfs, kv.ltc || D.stroke, at);
        }
      } else {
        throw new Error("unknown kind '" + kind + "'");
      }
    }

    pending.forEach(function (p) {
      var owner = byId[p[0]];
      if (!owner) throw new Error("arrow " + p[1].id + " binds to missing element " + p[0]);
      if (!owner.boundElements) owner.boundElements = [];
      var dup = owner.boundElements.some(function (b) { return b.id === p[1].id; });
      if (!dup) owner.boundElements.push(p[1]);
    });

    var scene = {};
    Object.keys(header).forEach(function (k) { scene[k] = header[k]; });
    scene.elements = els;
    return scene;
  }

  var EXCS = { dump: dump, build: build };
  if (typeof module !== "undefined" && module.exports) module.exports = EXCS;
  root.EXCS = EXCS;
})(typeof globalThis !== "undefined" ? globalThis : this);
