import {
  MOBILE_CAPABILITIES, PHASE1_CAPABILITIES, parseCommand,
  type AppBuildStatus, type AvailableSessionSnapshot, type Command, type CommandParams, type DiagnosticSnapshot,
  type HeartRateStatus, type LocationProbeStatus, type NativeEvent, type ObservationPage, type PermissionStatus,
  type RecorderLocationObservation, type SessionSnapshot, type StatusRow, type WorkoutMetrics,
} from '../../../src/shared/mobile'
import type { BridgeTransport } from './client'

const now = () => new Date().toISOString()
const row = <T extends Readonly<Record<string, unknown>>>(id: string, label: string, status: 'ok' | 'waiting' | 'unavailable' | 'error', reason: string, details: T): StatusRow<T> => ({ id, label, status, reason, observedAt: status === 'unavailable' ? null : now(), freshness: status === 'unavailable' ? 'never' : 'fresh', details })
const metrics = (): WorkoutMetrics => ({ activeDurationMs: 18 * 60_000 + 32_000, elapsedDurationMs: 19 * 60_000 + 12_000, distanceM: 7120, averageSpeedMps: 6.4, currentSpeedMps: 7.2, currentSpeedObservedAt: now(), altitudeM: 38, elevationGainM: 84, heartRateBpm: 142, heartRateObservedAt: now(), locationQuality: 'good', heartRateQuality: 'live' })

export const createSimulatorTransport = (fault: string | null = null): BridgeTransport => {
  let eventSequence = 4
  let revision = 0
  let sessionState: AvailableSessionSnapshot['state'] = 'idle'
  let sessionId: string | null = null
  let subscriptionId: string | null = null
  const bundled = { buildId: 'bundled-1', source: 'bundled' as const, engineBuildId: 'ride-metrics-v1' }
  let builds: AppBuildStatus = { active: bundled, previous: null, bundled, downloaded: [], pendingActivationBuildId: null, lastFailure: null }
  let configuredSource: { kind: 'development'; url: string } | { kind: 'bundled'; buildId: string } = { kind: 'bundled', buildId: 'bundled-1' }
  const route = [[37.7749,-122.4194],[37.7752,-122.4188],[37.7757,-122.4181],[37.7761,-122.4173],[37.7765,-122.4165],[37.7769,-122.4157]] as const
  const observations: RecorderLocationObservation[] = route.map(([latitudeDegrees, longitudeDegrees], index) => ({ kind: 'location', sessionId: 'sim-ride-1', sequence: index + 1, monotonicTimestampMs: index * 1000, source: 'coreLocation', sourceTimestamp: new Date(Date.now() - (route.length - index) * 1000).toISOString(), receivedAt: now(), latitudeDegrees, longitudeDegrees, horizontalAccuracyM: 5, altitudeM: 20 + index, verticalAccuracyM: 4, speedMps: 7.2, speedAccuracyMps: .5, courseDegrees: 42, courseAccuracyDegrees: 5, floorLevel: null, isSimulatedBySoftware: true, isProducedByAccessory: false }))
  const session = (): SessionSnapshot => fault === 'legacy-shell' ? { sessionId: null, state: 'idle', revision: 0, durableSequence: eventSequence, recorderAvailability: 'unavailable', recorderUnavailableReason: 'Update the installed native shell to enable recording.', pinnedEngine: null, capturedAt: now() } : {
    sessionId, state: sessionState, revision, durableSequence: sessionId ? observations.length : 0, recorderAvailability: 'available', recorderUnavailableReason: '', pinnedEngine: sessionId ? { buildId: 'ride-metrics-v1', apiVersion: 1, checkpointSchemaVersion: 1 } : null,
    sport: sessionId ? 'cycling' : null, startedAt: sessionId ? new Date(Date.now() - 20 * 60_000).toISOString() : null, finishedAt: sessionState === 'finished' ? now() : null, lastTransitionAt: sessionId ? now() : null,
    observationSequence: sessionId ? observations.length : 0, recovery: { required: sessionState === 'interrupted', interruptionStartedAt: sessionState === 'interrupted' ? new Date(Date.now() - 60_000).toISOString() : null, reason: sessionState === 'interrupted' ? 'Simulator process restart fixture' : null }, metrics: sessionId ? metrics() : { ...metrics(), activeDurationMs: 0, elapsedDurationMs: 0, distanceM: 0, elevationGainM: 0, averageSpeedMps: null, currentSpeedMps: null, altitudeM: null, heartRateBpm: null, locationQuality: 'waiting', heartRateQuality: 'unconfigured' }, capturedAt: now(),
  }
  let permissionState: PermissionStatus = { location: row('location', 'Location', 'waiting', 'Permission has not been requested.', { authorization: 'notDetermined' as const, precise: null }), bluetooth: row('bluetooth', 'Bluetooth heart rate', 'waiting', 'Permission has not been requested.', { authorization: 'notDetermined' as const, power: 'unknown' as const }), promptsAutomatically: false }
  let locationState: LocationProbeStatus = { availability: 'available', state: 'inactive', reason: 'Diagnostic location probe is idle.', probeId: null, startedAt: null, expiresAt: null, backgroundMode: null, backgroundDeliveryActive: false, appLifecycle: 'active', receivedCount: 0, acceptedCount: 0, rejectedCount: 0, lastRejectionReason: null, retainedCount: 0, oldestCursor: null, latestCursor: null, latestObservation: null, lastError: null }
  const monitor = { deviceId: 'sim-hr-strap', name: 'Simulator HR Strap', rssi: -48, lastSeenAt: now(), isConnectable: true, advertisedServiceUuids: ['180D'] }
  let heartRateState: HeartRateStatus = { availability: 'available', state: 'inactive', reason: 'No monitor connected; recording remains available.', scanEndsAt: null, devices: [], connectionId: null, connectedDevice: null, backgroundModeConfigured: true, appLifecycle: 'active', receivedCount: 0, parseErrorCount: 0, reconnectCount: 0, retainedCount: 0, oldestCursor: null, latestCursor: null, latestMeasurement: null, lastError: null }
  const diagnostics = (): DiagnosticSnapshot => ({ capturedAt: now(), eventSequence, rows: [
    row('webBuild', 'Web build', 'ok', 'Simulator bundled UI loaded.', { uiSource: { configured: configuredSource, targetUrl: configuredSource.kind === 'development' ? configuredSource.url : `workout-app://${configuredSource.buildId}/ui/index.html`, loadedUrl: configuredSource.kind === 'development' ? configuredSource.url : `workout-app://${configuredSource.buildId}/ui/index.html`, loadState: 'ready', currentFailure: null, lastFailureHistory: null, generation: 1 } }),
    row('bridge', 'Native bridge', fault === 'bridge-error' ? 'error' : 'ok', fault === 'bridge-error' ? 'Injected validation fault.' : 'Round trips are responding.', { latencyMs: 7 }),
    row('location', 'Location service', permissionState.location.status, permissionState.location.reason, {}),
    row('heart-rate', 'Heart-rate sensor', heartRateState.state === 'connected' ? 'ok' : 'waiting', heartRateState.reason, {}),
    row('recorder', 'Workout recorder', fault === 'legacy-shell' ? 'unavailable' : sessionState === 'recording' ? 'ok' : 'waiting', fault === 'legacy-shell' ? 'Native shell update required.' : `Recorder is ${sessionState}.`, {}),
    row('storage', 'Workout storage', 'ok', 'Durable SQLite writes are current.', {}), row('engine', 'Metrics engine', 'ok', 'Pinned ride-metrics-v1 engine is current.', {}),
  ] })
  const snapshot = () => ({ sequence: eventSequence, session: session(), permissions: permissionState, location: locationState, heartRate: heartRateState, diagnostics: diagnostics(), appBuild: builds })
  const reply = (command: Command, result: unknown) => window.setTimeout(() => window.WorkoutAnalyzeNative?.receiveReply({ protocolVersion: 1, requestId: command.requestId, ok: true, result }), fault === 'timeout' ? 20_000 : 15)
  const emit = (type: NativeEvent['type'], payload: NativeEvent['payload']) => { eventSequence += 1; const event: NativeEvent = { protocolVersion: 1, sessionId, sequence: eventSequence, type, payload }; window.setTimeout(() => window.WorkoutAnalyzeNative?.receiveEvent(event), 20) }
  const mutation = (command: Command, state: AvailableSessionSnapshot['state']) => { sessionState = state; revision += 1; if (!sessionId) sessionId = 'sim-ride-1'; const value = session(); reply(command, value); emit('session.updated', value) }
  const page = (afterSequence: number | null): ObservationPage => { const items = observations.filter((item) => item.sequence > (afterSequence ?? 0)); return { items, nextSequence: items.at(-1)?.sequence ?? null, oldestAvailableSequence: 1, latestDurableSequence: observations.length, hasMore: false, droppedBeforeSequence: false } }
  const savedSummary = () => ({ savedWorkoutId: 'sim-saved-ride-1', sessionId: 'sim-ride-1', sport: 'cycling' as const, startedAt: new Date(Date.now() - 20 * 60_000).toISOString(), finishedAt: now(), durationMs: metrics().activeDurationMs, observationCount: observations.length, latestSequence: observations.length, metrics: metrics(), hasFatalIssue: false })

  return { kind: 'simulator', label: fault ? `Browser simulator · ${fault}` : 'Browser simulator · recorder fixture', post(raw) {
    const command = parseCommand(raw)
    switch (command.method) {
      case 'bridge.hello': reply(command, { shellVersion: 'sim-1.0.0', protocolVersion: 1, engineApiVersion: 1, checkpointSchemaVersion: 1, capabilities: fault === 'legacy-shell' ? PHASE1_CAPABILITIES : fault === 'no-database' ? MOBILE_CAPABILITIES.filter((capability) => !capability.startsWith('database.')) : MOBILE_CAPABILITIES, unavailableCapabilities: fault === 'legacy-shell' ? [{ capability: 'workout.recorder', reason: 'Native update required' }] : [] }); break
      case 'bridge.ping': reply(command, { nonce: (command.params as CommandParams['bridge.ping']).nonce, nativeReceivedAt: now(), nativeSentAt: now() }); break
      case 'session.snapshot': reply(command, session()); break
      case 'bridge.snapshot': reply(command, snapshot()); break
      case 'permissions.status': reply(command, permissionState); break
      case 'permissions.request': { const permission = (command.params as CommandParams['permissions.request']).permission; permissionState = permission === 'locationWhenInUse' ? { ...permissionState, location: row('location', 'Location', 'ok', 'Precise when-in-use location granted.', { authorization: 'whenInUse', precise: true }) } : { ...permissionState, bluetooth: row('bluetooth', 'Bluetooth heart rate', 'ok', 'Bluetooth available.', { authorization: 'allowed', power: 'poweredOn' }) }; reply(command, permissionState); emit('permissions.updated', permissionState); break }
      case 'workout.start': mutation(command, 'recording'); break
      case 'workout.pause': mutation(command, 'paused'); break
      case 'workout.resume': mutation(command, 'recording'); break
      case 'workout.finish': { sessionState = 'finished'; revision += 1; const value = session(); reply(command, { session: value, savedWorkoutId: 'sim-saved-ride-1' }); emit('session.updated', value); break }
      case 'workout.recover': { const action = (command.params as CommandParams['workout.recover']).action; sessionState = action === 'resume' ? 'recording' : 'finished'; revision += 1; const value = session(); reply(command, action === 'finish' ? { session: value, savedWorkoutId: 'sim-saved-ride-1' } : value); emit('session.updated', value); break }
      case 'workout.export': { const format = (command.params as CommandParams['workout.export']).format; reply(command, { exportId: `sim-${format}`, presented: true, format }); break }
      case 'observations.subscribe': { subscriptionId = 'sim-observations-1'; reply(command, { subscriptionId, afterSequence: 0, latestDurableSequence: observations.length }); break }
      case 'observations.unsubscribe': subscriptionId = null; reply(command, { removed: true }); break
      case 'observations.read': reply(command, page((command.params as CommandParams['observations.read']).afterSequence)); break
      case 'journal.read': { const after = (command.params as CommandParams['journal.read']).afterJournalSequence; const firstSequence = (after ?? 0) + 1; const items = firstSequence <= observations.length ? [{ formatVersion: 1, eventId: `sim-journal-${firstSequence}`, sessionId: 'sim-ride-1', journalSequence: firstSequence, kind: 'coreLocation.delivered', sourceTimestamp: observations[firstSequence - 1]?.sourceTimestamp ?? null, receivedAt: now(), monotonicTimestampMs: (firstSequence - 1) * 1000, provenance: { origin: 'syntheticFixture', sourceId: 'simulator', monotonicClockId: 'sim-clock', lineage: null }, batch: null, payload: { encoding: 'json', value: { fixtureIndex: firstSequence } } }] : []; reply(command, { afterJournalSequence: after, items, nextJournalSequence: items[0]?.journalSequence ?? null, oldestAvailableJournalSequence: 1, latestJournalSequence: observations.length, hasMore: firstSequence < observations.length, droppedBeforeJournalSequence: false }); break }
      case 'archive.list': { const items = sessionState === 'finished' ? [savedSummary()] : []; reply(command, { afterCursor: null, items, nextCursor: null, hasMore: false, snapshotAt: now() }); break }
      case 'archive.detail': { const afterSequence = (command.params as CommandParams['archive.detail']).afterSequence; reply(command, { summary: savedSummary(), pinnedEngine: { buildId: 'ride-metrics-v1', apiVersion: 1, checkpointSchemaVersion: 1 }, recordingFormatVersion: 1, units: 'SI', derivation: { algorithmId: 'ride-metrics-v1', engineBuildId: 'ride-metrics-v1', configId: 'default-v1', firstInputSequence: 1, lastInputSequence: observations.length }, observations: { ...page(afterSequence), afterSequence } }); break }
      case 'location.status': reply(command, locationState); break
      case 'location.start': { const params = command.params as CommandParams['location.start']; const latest = observations.at(-1)!; locationState = { ...locationState, state: 'active', reason: 'Diagnostic probe active.', probeId: 'sim-probe', startedAt: now(), expiresAt: new Date(Date.now() + params.maxDurationSeconds * 1000).toISOString(), backgroundMode: params.backgroundMode, backgroundDeliveryActive: params.backgroundMode === 'continueWhenBackgrounded', receivedCount: 1, acceptedCount: 1, retainedCount: 1, oldestCursor: 1, latestCursor: 1, latestObservation: { cursor: 1, source: latest.source, sourceTimestamp: latest.sourceTimestamp, receivedAt: latest.receivedAt, latitudeDegrees: latest.latitudeDegrees, longitudeDegrees: latest.longitudeDegrees, horizontalAccuracyM: latest.horizontalAccuracyM, altitudeM: latest.altitudeM, verticalAccuracyM: latest.verticalAccuracyM, speedMps: latest.speedMps, speedAccuracyMps: latest.speedAccuracyMps, courseDegrees: latest.courseDegrees, courseAccuracyDegrees: latest.courseAccuracyDegrees, floorLevel: latest.floorLevel, isSimulatedBySoftware: latest.isSimulatedBySoftware, isProducedByAccessory: latest.isProducedByAccessory } }; reply(command, locationState); break }
      case 'location.stop': locationState = { ...locationState, state: 'inactive', backgroundDeliveryActive: false }; reply(command, locationState); break
      case 'location.read': reply(command, { items: locationState.latestObservation ? [locationState.latestObservation] : [], nextCursor: locationState.latestCursor, oldestAvailableCursor: locationState.oldestCursor, hasMore: false, droppedBeforeCursor: false }); break
      case 'heartRate.status': reply(command, heartRateState); break
      case 'heartRate.scan': heartRateState = { ...heartRateState, state: 'scanning', reason: 'Found one standard Heart Rate Service monitor.', scanEndsAt: new Date(Date.now() + 10_000).toISOString(), devices: [monitor] }; reply(command, heartRateState); break
      case 'heartRate.stopScan': heartRateState = { ...heartRateState, state: 'inactive', scanEndsAt: null }; reply(command, heartRateState); break
      case 'heartRate.connect': { const measurement = { cursor: 1, connectionId: 'sim-hr-connection', deviceId: monitor.deviceId, receivedAt: now(), bpm: 142, valueFormat: 'uint8' as const, sensorContact: 'detected' as const, energyExpendedKJ: null, rrIntervalsSeconds: [.42], rawFlags: 6 }; heartRateState = { ...heartRateState, state: 'connected', reason: 'Monitor connected.', scanEndsAt: null, connectionId: measurement.connectionId, connectedDevice: monitor, latestMeasurement: measurement, receivedCount: 1, retainedCount: 1, oldestCursor: 1, latestCursor: 1 }; reply(command, heartRateState); emit('heartRate.updated', heartRateState); break }
      case 'heartRate.disconnect': heartRateState = { ...heartRateState, state: 'inactive', reason: 'Monitor disconnected; recording continues.', connectionId: null, connectedDevice: null }; reply(command, heartRateState); break
      case 'heartRate.read': reply(command, { items: heartRateState.latestMeasurement ? [heartRateState.latestMeasurement] : [], nextCursor: heartRateState.latestCursor, oldestAvailableCursor: heartRateState.oldestCursor, hasMore: false, droppedBeforeCursor: false }); break
      case 'diagnostics.snapshot': reply(command, diagnostics()); break
      case 'diagnostics.runChecks': reply(command, { workoutStateUnchanged: true, results: ['bridgePing','capabilityCompatibility','diagnosticStorage','engineFixture'].map((id) => ({ id, outcome: 'pass', reason: 'Isolated check passed without changing workout state.', startedAt: now(), finishedAt: now(), namespace: id === 'engineFixture' ? 'engine-fixture' : 'diagnostics' })) }); break
      case 'diagnostics.export': reply(command, { presented: true, exportId: 'sim-diagnostics' }); break
      case 'appBuild.status': reply(command, builds); break
      case 'appBuild.download': { const build = { buildId: 'downloaded-2', source: 'installed' as const, engineBuildId: 'ride-metrics-v1' }; builds = { ...builds, downloaded: [build] }; reply(command, { build, activated: false }); break }
      case 'appBuild.activate': { const active = builds.downloaded[0] ?? bundled; builds = { ...builds, previous: builds.active, active }; reply(command, { active, reloadRequired: true }); emit('appBuild.updated', builds); break }
      case 'appBuild.rollback': { const active = (command.params as CommandParams['appBuild.rollback']).target === 'previous' ? builds.previous ?? bundled : bundled; builds = { ...builds, active }; reply(command, { active, reloadRequired: true }); break }
      case 'devSource.configure': { const url = (command.params as CommandParams['devSource.configure']).url; if (url) configuredSource = { kind: 'development', url }; reply(command, { source: url ? { kind: 'development', url } : { kind: 'bundled' }, reloadRequired: true }); break }
      case 'ui.reload': reply(command, { accepted: true }); break
    }
  } }
}
