// Derives src/lib-wasm.zig from OpenTUI's src/lib.zig by dropping every
// top-level declaration that touches a subsystem with no wasm implementation
// (audio: miniaudio + threads; host clipboard: X11/Wayland/AppKit worker
// threads). The dropped `export fn`s simply do not exist in the wasm module;
// the JS FFI backend (src/wasm-ffi.ts) substitutes a throwing stub for any
// symbol the TypeScript side declares but the module does not export.
//
// Text-level on purpose: it keeps working when upstream adds exports to those
// subsystems, and leaves the vendored tree otherwise untouched.

const DROPPED_MODULES = ["native_audio", "clipboard"] as const

// The JS side has to place call arguments inside linear memory, so it needs
// the module's own libc allocator.
const WASM_EXTRAS = `
extern "c" fn malloc(size: usize) ?*anyopaque;
extern "c" fn free(ptr: ?*anyopaque) void;

export fn wasmTermAlloc(size: usize) ?*anyopaque {
    return malloc(size);
}

export fn wasmTermFree(ptr: ?*anyopaque) void {
    free(ptr);
}
`

const TOP_LEVEL = /^(pub |export |extern |inline |fn |const |var |test |comptime )/

export interface GenResult {
  source: string
  droppedExports: string[]
  droppedOther: string[]
}

function chunks(source: string): string[] {
  const out: string[] = []
  let current: string[] = []
  for (const line of source.split("\n")) {
    if (TOP_LEVEL.test(line) && current.length > 0) {
      out.push(current.join("\n"))
      current = []
    }
    current.push(line)
  }
  out.push(current.join("\n"))
  return out
}

function declName(chunk: string): { name: string; exported: boolean } | undefined {
  const first = chunk.split("\n", 1)[0] ?? ""
  const match = first.match(/^(?:pub )?(export )?(?:inline )?(?:fn|const|var) ([A-Za-z_][A-Za-z0-9_]*)/)
  if (!match) return undefined
  return { name: match[2]!, exported: match[1] !== undefined }
}

export function generate(lib: string): GenResult {
  const droppedNames = new Set<string>(DROPPED_MODULES)
  const droppedExports: string[] = []
  const droppedOther: string[] = []
  let parts = chunks(lib)
  for (;;) {
    const pattern = new RegExp(`(?<![.\\w"])(?:${[...droppedNames].join("|")})(?![\\w"])`)
    let changed = false
    parts = parts.filter((chunk) => {
      // `_ = native_audio;` style keep-alive lines are stripped below, not a reason to drop.
      const body = chunk
        .split("\n")
        .filter((line) => !/^\s*_ = [A-Za-z_]+;\s*$/.test(line))
        .join("\n")
      if (!pattern.test(body)) return true
      const decl = declName(chunk)
      if (decl) {
        droppedNames.add(decl.name)
        ;(decl.exported ? droppedExports : droppedOther).push(decl.name)
      } else droppedOther.push(chunk.split("\n", 1)[0]!.slice(0, 60))
      changed = true
      return false
    })
    if (!changed) break
  }
  const keepAlive = new RegExp(`^\\s*_ = (?:${DROPPED_MODULES.join("|")});\\s*$`)
  const source =
    "// GENERATED by wasm-term/ports/opencode/native/gen-lib-wasm.ts from lib.zig. Do not edit.\n" +
    parts
      .join("\n")
      .split("\n")
      .filter((line) => !keepAlive.test(line))
      .join("\n") +
    WASM_EXTRAS
  return { source, droppedExports, droppedOther }
}

if (import.meta.main) {
  const [input, output] = process.argv.slice(2)
  if (!input || !output) throw new Error("usage: gen-lib-wasm.ts <lib.zig> <lib-wasm.zig>")
  const result = generate(await Bun.file(input).text())
  await Bun.write(output, result.source)
  console.log(
    `lib-wasm.zig: dropped ${result.droppedExports.length} exports, ${result.droppedOther.length} other decls (${result.droppedOther.join(", ")})`,
  )
}
