/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiTripsRouteImport } from './routes/api/trips'
import { Route as ApiWorkoutsRouteImport } from './routes/api/workouts'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as ApiMediaImportsRouteImport } from './routes/api/media/imports'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiTripsTripIdRouteImport } from './routes/api/trips/$tripId'
import { Route as MediaIdRepresentationRouteImport } from './routes/media/$id/$representation'
import { Route as TripsTripIdRoutesWorkoutIdRouteImport } from './routes/trips.$tripId_.routes.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripsRoute = ApiTripsRouteImport.update({
  id: '/api/trips',
  path: '/api/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutsRoute = ApiWorkoutsRouteImport.update({
  id: '/api/workouts',
  path: '/api/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaImportsRoute = ApiMediaImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiTripsTripIdRoute = ApiTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => ApiTripsRoute,
} as any)
const MediaIdRepresentationRoute = MediaIdRepresentationRouteImport.update({
  id: '/media/$id/$representation',
  path: '/media/$id/$representation',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoutesWorkoutIdRoute =
  TripsTripIdRoutesWorkoutIdRouteImport.update({
    id: '/trips/$tripId_/routes/$workoutId',
    path: '/trips/$tripId/routes/$workoutId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/api/workouts': typeof ApiWorkoutsRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/api/media/imports': typeof ApiMediaImportsRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRoute
  '/media/$id/$representation': typeof MediaIdRepresentationRoute
  '/trips/$tripId/routes/$workoutId': typeof TripsTripIdRoutesWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/api/workouts': typeof ApiWorkoutsRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/api/media/imports': typeof ApiMediaImportsRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRoute
  '/media/$id/$representation': typeof MediaIdRepresentationRoute
  '/trips/$tripId/routes/$workoutId': typeof TripsTripIdRoutesWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/api/workouts': typeof ApiWorkoutsRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/api/media/imports': typeof ApiMediaImportsRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRoute
  '/media/$id/$representation': typeof MediaIdRepresentationRoute
  '/trips/$tripId_/routes/$workoutId': typeof TripsTripIdRoutesWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/media'
    | '/api/trips'
    | '/api/workouts'
    | '/trips/$tripId'
    | '/api/media/imports'
    | '/api/media/upload'
    | '/api/trips/$tripId'
    | '/media/$id/$representation'
    | '/trips/$tripId/routes/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/media'
    | '/api/trips'
    | '/api/workouts'
    | '/trips/$tripId'
    | '/api/media/imports'
    | '/api/media/upload'
    | '/api/trips/$tripId'
    | '/media/$id/$representation'
    | '/trips/$tripId/routes/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/api/media'
    | '/api/trips'
    | '/api/workouts'
    | '/trips/$tripId'
    | '/api/media/imports'
    | '/api/media/upload'
    | '/api/trips/$tripId'
    | '/media/$id/$representation'
    | '/trips/$tripId_/routes/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  ApiTripsRoute: typeof ApiTripsRouteWithChildren
  ApiWorkoutsRoute: typeof ApiWorkoutsRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  MediaIdRepresentationRoute: typeof MediaIdRepresentationRoute
  TripsTripIdRoutesWorkoutIdRoute: typeof TripsTripIdRoutesWorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trips': {
      id: '/api/trips'
      path: '/api/trips'
      fullPath: '/api/trips'
      preLoaderRoute: typeof ApiTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workouts': {
      id: '/api/workouts'
      path: '/api/workouts'
      fullPath: '/api/workouts'
      preLoaderRoute: typeof ApiWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/imports': {
      id: '/api/media/imports'
      path: '/imports'
      fullPath: '/api/media/imports'
      preLoaderRoute: typeof ApiMediaImportsRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/trips/$tripId': {
      id: '/api/trips/$tripId'
      path: '/$tripId'
      fullPath: '/api/trips/$tripId'
      preLoaderRoute: typeof ApiTripsTripIdRouteImport
      parentRoute: typeof ApiTripsRoute
    }
    '/media/$id/$representation': {
      id: '/media/$id/$representation'
      path: '/media/$id/$representation'
      fullPath: '/media/$id/$representation'
      preLoaderRoute: typeof MediaIdRepresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId_/routes/$workoutId': {
      id: '/trips/$tripId_/routes/$workoutId'
      path: '/trips/$tripId/routes/$workoutId'
      fullPath: '/trips/$tripId/routes/$workoutId'
      preLoaderRoute: typeof TripsTripIdRoutesWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiMediaRouteChildren {
  ApiMediaImportsRoute: typeof ApiMediaImportsRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaImportsRoute: ApiMediaImportsRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

interface ApiTripsRouteChildren {
  ApiTripsTripIdRoute: typeof ApiTripsTripIdRoute
}

const ApiTripsRouteChildren: ApiTripsRouteChildren = {
  ApiTripsTripIdRoute: ApiTripsTripIdRoute,
}

const ApiTripsRouteWithChildren = ApiTripsRoute._addFileChildren(
  ApiTripsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  ApiTripsRoute: ApiTripsRouteWithChildren,
  ApiWorkoutsRoute: ApiWorkoutsRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  MediaIdRepresentationRoute: MediaIdRepresentationRoute,
  TripsTripIdRoutesWorkoutIdRoute: TripsTripIdRoutesWorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
